/*
EasyAPI REST Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.1
Contact: easyapi@easydns.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegDataExtraNU type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegDataExtraNU{}

// RegDataExtraNU struct for RegDataExtraNU
type RegDataExtraNU struct {
	// Registrant type
	RegistrantType string `json:"registrant_type"`
	// ID Card Number
	IdCardNumber string `json:"id_card_number"`
	// Value Added Tax (VAT) number
	RegistrantVatId *string `json:"registrant_vat_id,omitempty"`
	// Business number
	RegistrationNumber string `json:"registration_number"`
}

type _RegDataExtraNU RegDataExtraNU

// NewRegDataExtraNU instantiates a new RegDataExtraNU object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegDataExtraNU(registrantType string, idCardNumber string, registrationNumber string) *RegDataExtraNU {
	this := RegDataExtraNU{}
	this.RegistrantType = registrantType
	this.IdCardNumber = idCardNumber
	this.RegistrationNumber = registrationNumber
	return &this
}

// NewRegDataExtraNUWithDefaults instantiates a new RegDataExtraNU object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegDataExtraNUWithDefaults() *RegDataExtraNU {
	this := RegDataExtraNU{}
	return &this
}

// GetRegistrantType returns the RegistrantType field value
func (o *RegDataExtraNU) GetRegistrantType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistrantType
}

// GetRegistrantTypeOk returns a tuple with the RegistrantType field value
// and a boolean to check if the value has been set.
func (o *RegDataExtraNU) GetRegistrantTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistrantType, true
}

// SetRegistrantType sets field value
func (o *RegDataExtraNU) SetRegistrantType(v string) {
	o.RegistrantType = v
}

// GetIdCardNumber returns the IdCardNumber field value
func (o *RegDataExtraNU) GetIdCardNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdCardNumber
}

// GetIdCardNumberOk returns a tuple with the IdCardNumber field value
// and a boolean to check if the value has been set.
func (o *RegDataExtraNU) GetIdCardNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdCardNumber, true
}

// SetIdCardNumber sets field value
func (o *RegDataExtraNU) SetIdCardNumber(v string) {
	o.IdCardNumber = v
}

// GetRegistrantVatId returns the RegistrantVatId field value if set, zero value otherwise.
func (o *RegDataExtraNU) GetRegistrantVatId() string {
	if o == nil || IsNil(o.RegistrantVatId) {
		var ret string
		return ret
	}
	return *o.RegistrantVatId
}

// GetRegistrantVatIdOk returns a tuple with the RegistrantVatId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegDataExtraNU) GetRegistrantVatIdOk() (*string, bool) {
	if o == nil || IsNil(o.RegistrantVatId) {
		return nil, false
	}
	return o.RegistrantVatId, true
}

// HasRegistrantVatId returns a boolean if a field has been set.
func (o *RegDataExtraNU) HasRegistrantVatId() bool {
	if o != nil && !IsNil(o.RegistrantVatId) {
		return true
	}

	return false
}

// SetRegistrantVatId gets a reference to the given string and assigns it to the RegistrantVatId field.
func (o *RegDataExtraNU) SetRegistrantVatId(v string) {
	o.RegistrantVatId = &v
}

// GetRegistrationNumber returns the RegistrationNumber field value
func (o *RegDataExtraNU) GetRegistrationNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistrationNumber
}

// GetRegistrationNumberOk returns a tuple with the RegistrationNumber field value
// and a boolean to check if the value has been set.
func (o *RegDataExtraNU) GetRegistrationNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistrationNumber, true
}

// SetRegistrationNumber sets field value
func (o *RegDataExtraNU) SetRegistrationNumber(v string) {
	o.RegistrationNumber = v
}

func (o RegDataExtraNU) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegDataExtraNU) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["registrant_type"] = o.RegistrantType
	toSerialize["id_card_number"] = o.IdCardNumber
	if !IsNil(o.RegistrantVatId) {
		toSerialize["registrant_vat_id"] = o.RegistrantVatId
	}
	toSerialize["registration_number"] = o.RegistrationNumber
	return toSerialize, nil
}

func (o *RegDataExtraNU) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"registrant_type",
		"id_card_number",
		"registration_number",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegDataExtraNU := _RegDataExtraNU{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegDataExtraNU)

	if err != nil {
		return err
	}

	*o = RegDataExtraNU(varRegDataExtraNU)

	return err
}

type NullableRegDataExtraNU struct {
	value *RegDataExtraNU
	isSet bool
}

func (v NullableRegDataExtraNU) Get() *RegDataExtraNU {
	return v.value
}

func (v *NullableRegDataExtraNU) Set(val *RegDataExtraNU) {
	v.value = val
	v.isSet = true
}

func (v NullableRegDataExtraNU) IsSet() bool {
	return v.isSet
}

func (v *NullableRegDataExtraNU) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegDataExtraNU(val *RegDataExtraNU) *NullableRegDataExtraNU {
	return &NullableRegDataExtraNU{value: val, isSet: true}
}

func (v NullableRegDataExtraNU) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegDataExtraNU) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


