/*
EasyAPI REST Services API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.1
Contact: easyapi@easydns.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestModelMailmapCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestModelMailmapCreate{}

// RequestModelMailmapCreate struct for RequestModelMailmapCreate
type RequestModelMailmapCreate struct {
	// Alias part of mailmap address (for example: 'test' from test@example.com)
	Alias string `json:"alias"`
	// The hostname (without domain name) the mailmap should be created under
	Host string `json:"host"`
	// The email address to forward the mailmaps emails to
	Destination string `json:"destination"`
	// Setting this to 0 will disable the mailmap from forwarding mail
	Active int32 `json:"active"`
}

type _RequestModelMailmapCreate RequestModelMailmapCreate

// NewRequestModelMailmapCreate instantiates a new RequestModelMailmapCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestModelMailmapCreate(alias string, host string, destination string, active int32) *RequestModelMailmapCreate {
	this := RequestModelMailmapCreate{}
	this.Alias = alias
	this.Host = host
	this.Destination = destination
	this.Active = active
	return &this
}

// NewRequestModelMailmapCreateWithDefaults instantiates a new RequestModelMailmapCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestModelMailmapCreateWithDefaults() *RequestModelMailmapCreate {
	this := RequestModelMailmapCreate{}
	return &this
}

// GetAlias returns the Alias field value
func (o *RequestModelMailmapCreate) GetAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Alias
}

// GetAliasOk returns a tuple with the Alias field value
// and a boolean to check if the value has been set.
func (o *RequestModelMailmapCreate) GetAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alias, true
}

// SetAlias sets field value
func (o *RequestModelMailmapCreate) SetAlias(v string) {
	o.Alias = v
}

// GetHost returns the Host field value
func (o *RequestModelMailmapCreate) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *RequestModelMailmapCreate) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *RequestModelMailmapCreate) SetHost(v string) {
	o.Host = v
}

// GetDestination returns the Destination field value
func (o *RequestModelMailmapCreate) GetDestination() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value
// and a boolean to check if the value has been set.
func (o *RequestModelMailmapCreate) GetDestinationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Destination, true
}

// SetDestination sets field value
func (o *RequestModelMailmapCreate) SetDestination(v string) {
	o.Destination = v
}

// GetActive returns the Active field value
func (o *RequestModelMailmapCreate) GetActive() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *RequestModelMailmapCreate) GetActiveOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *RequestModelMailmapCreate) SetActive(v int32) {
	o.Active = v
}

func (o RequestModelMailmapCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestModelMailmapCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alias"] = o.Alias
	toSerialize["host"] = o.Host
	toSerialize["destination"] = o.Destination
	toSerialize["active"] = o.Active
	return toSerialize, nil
}

func (o *RequestModelMailmapCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alias",
		"host",
		"destination",
		"active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestModelMailmapCreate := _RequestModelMailmapCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestModelMailmapCreate)

	if err != nil {
		return err
	}

	*o = RequestModelMailmapCreate(varRequestModelMailmapCreate)

	return err
}

type NullableRequestModelMailmapCreate struct {
	value *RequestModelMailmapCreate
	isSet bool
}

func (v NullableRequestModelMailmapCreate) Get() *RequestModelMailmapCreate {
	return v.value
}

func (v *NullableRequestModelMailmapCreate) Set(val *RequestModelMailmapCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestModelMailmapCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestModelMailmapCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestModelMailmapCreate(val *RequestModelMailmapCreate) *NullableRequestModelMailmapCreate {
	return &NullableRequestModelMailmapCreate{value: val, isSet: true}
}

func (v NullableRequestModelMailmapCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestModelMailmapCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


