/*
EasyAPI REST Services API

Testing DeleteAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_DeleteAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DeleteAPIService DelUXZoneRec", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domain string
		var id string

		httpRes, err := apiClient.DeleteAPI.DelUXZoneRec(context.Background(), domain, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeleteAPIService DelZoneRec", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domain string
		var id string

		httpRes, err := apiClient.DeleteAPI.DelZoneRec(context.Background(), domain, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeleteAPIService DeleteDomain", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domain string

		resp, httpRes, err := apiClient.DeleteAPI.DeleteDomain(context.Background(), domain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeleteAPIService DeleteMailmap", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domain string
		var mailmapId int32

		resp, httpRes, err := apiClient.DeleteAPI.DeleteMailmap(context.Background(), domain, mailmapId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
